# Complete library list for rsconnect deployment
library(shiny)
library(shinydashboard)
library(DT)
library(plotly)
library(SingleCellExperiment)
library(SummarizedExperiment)
library(BiocGenerics)
library(S4Vectors)
library(ggplot2)
library(GGally)
library(dplyr)
library(shinycssloaders)
library(ggridges)
library(MASS)
library(rlang)
library(igraph)
library(FNN)
library(isotree)
library(scales)
library(methods)
library(stats)
library(utils)
library(grDevices)
library(graphics)

# Source support functions
source("support/argumentCheck.R")
source("support/projectPCA.R")
source("support/generateColors.R")
source("support/plotCellTypePCA_app.R")
source("support/calculateGraphIntegration_app.R")
source("support/plotGraphIntegration_app.R")
source("support/detectAnomaly_app.R")
source("support/plotAnomaly_app.R")
source("support/calculateVarImpOverlap.R")
source("support/calculateDiscriminantSpace_app.R")
source("support/plotDiscriminantSpace_app.R")

# Load the datasets
query_cells <- readRDS("data/query_marrow_myeloid.rds")
reference_cells <- readRDS("data/reference_marrow_myeloid.rds")
reference_cells_subset <- readRDS("data/reference_subset_marrow_myeloid.rds")